name: Bug report
description: Report a reproducible bug.
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      placeholder: |
        1. Run ...
        2. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Wrkr version
      placeholder: main / commit SHA
